POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name": "NoMads",
    "genre": "hip-hop",
    "albums": [
        {
            "title": "Project-A",
            "release_date": "2018-07-27"
        }
    ]
}

###

GET http://localhost:8000/bands/222
